name: "deploy-docker-image"
description: "Deploys a docker image to my cloud"
inputs:
  context:
    description: "The folder to use as context"
    required: false
    default: "."
  domain:
    description: "Domain name"
    required: true
  port:
    description: "Port"
    required: false
  private:
    description: "Private"
    required: false
  volume:
    description: "Volume"
    required: false
  token:
    description: "GitHub personal access token"
    required: true
  test-command:
    description: "Command to test the docker image"
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: all
    - name: Set up Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3
    - name: Set up Metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}
        tags: |
          type=raw,value=${{ github.sha }}
          type=raw,value=latest
    - name: Build Image
      uses: docker/build-push-action@v5
      with:
        context: ${{ inputs.context }}
        load: true
        tags: ${{ steps.meta.outputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: Test
      if: ${{ inputs.test-command != '' }}
      run: ${{ inputs.test-command }}
      shell: bash
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Push Docker Image
      run: |
        docker push --all-tags ghcr.io/$GITHUB_REPOSITORY
      shell: bash
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
    - name: Get App Name
      id: get-app-name
      run: echo "app-name=$(echo ${GITHUB_REPOSITORY#*/})" >> $GITHUB_OUTPUT
      shell: bash
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
    - name: Deploy
      run: |
        gh workflow run deploy.yml \
          --repo 4lejandrito/cloud \
          -f name="${{ steps.get-app-name.outputs.app-name }}" \
          -f image="ghcr.io/$GITHUB_REPOSITORY:${{ github.sha }}" \
          -f domain="${{ inputs.domain }}" \
          -f port="${{ inputs.port }}" \
          -f private="${{ inputs.private }}" \
          -f volume="${{ inputs.volume }}" \
          -f source="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
    - name: Prune Docker Images
      uses: vlaurin/action-ghcr-prune@main
      with:
        token: ${{ inputs.token }}
        container: ${{ steps.get-app-name.outputs.app-name }}
        keep-last: 1
        prune-untagged: true
        prune-tags-regexes: .*
