name: "deploy-docker-image"
description: "Deploys a docker image to my cloud"
inputs:
  domain:
    description: "Domain name"
    required: true
  email:
    description: "Email"
    required: true
  port:
    description: "Port"
  private:
    description: "Private"
  volume:
    description: "Volume"
  token:
    description: "GitHub personal access token"

runs:
  using: "composite"
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Push Docker Image
      run: |
        docker push --all-tags ghcr.io/$GITHUB_REPOSITORY
      shell: bash
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
    - name: Get App Name
      id: get-app-name
      run: echo "app-name=$(echo ${GITHUB_REPOSITORY#*/})" >> $GITHUB_OUTPUT
      shell: bash
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
    - name: Deploy
      run: |
        gh workflow run deploy.yml \
          --repo 4lejandrito/cloud \
          -f name="${{ steps.get-app-name.outputs.app-name }}" \
          -f image="ghcr.io/$GITHUB_REPOSITORY:${{ github.sha }}" \
          -f domain="${{ inputs.domain }}" \
          -f email="${{ inputs.email }}" \
          -f port="${{ inputs.port }}" \
          -f private="${{ inputs.private }}" \
          -f volume="${{ inputs.volume }}"
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.token }}
    - name: Prune Docker Images
      if: ${{ inputs.token != '' }}
      uses: vlaurin/action-ghcr-prune@main
      with:
        token: ${{ inputs.token }}
        container: ${{ steps.get-app-name.outputs.app-name }}
        keep-last: 1
        prune-untagged: true
        prune-tags-regexes: .*
