name: "deploy-docker-image"
description: "Deploys a docker image to dokku"
inputs:
  key:
    description: "SSH private key"
    required: true
  prune-gh-pat:
    description: "GitHub personal access token to prune previous images"
    required: false
runs:
  using: "composite"
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Push Docker Image
      run: |
        docker push --all-tags ghcr.io/$GITHUB_REPOSITORY
      shell: bash
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
    - name: Get App Name
      id: get-app-name
      run: echo "::set-output name=app-name::$(echo ${GITHUB_REPOSITORY#*/})"
      shell: bash
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
    - name: Deploy to Dokku
      uses: dokku/github-action@master
      with:
        git_remote_url: ssh://dokku@4lejandrito.dev/${{ steps.get-app-name.outputs.app-name }}
        ssh_private_key: ${{ inputs.key }}
        deploy_docker_image: ghcr.io/${{ github.repository }}:${{ github.sha }}
    - name: Prune Docker Images
      if: ${{ inputs.prune-gh-pat != '' }}
      uses: vlaurin/action-ghcr-prune@main
      with:
        token: ${{ inputs.prune-gh-pat }}
        container: ${{ steps.get-app-name.outputs.app-name }}
        keep-last: 1
        untagged: true
        tag-regex: ".*"
