name: "deploy-docker-image"
description: "Deploys a docker image to dokku"
inputs:
  key:
    description: "SSH private key"
    required: true
  prune-gh-pat:
    description: "GitHub personal access token to prune previous images"
    required: false
runs:
  using: "composite"
  steps:
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - name: Push Docker Image
      run: |
        docker push --all-tags ghcr.io/$GITHUB_REPOSITORY
      shell: bash
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
    - name: Deploy to Dokku
      run: |
        mkdir -p ~/.ssh
        eval `ssh-agent -s`
        ssh-add - <<< "$SSH_PRIVATE_KEY"
        ssh-keyscan 4lejandrito.dev >> ~/.ssh/known_hosts
        ssh dokku@4lejandrito.dev git:from-image ${GITHUB_REPOSITORY#*/} ghcr.io/$GITHUB_REPOSITORY:sha-$(git rev-parse --short HEAD)
      shell: bash
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        SSH_PRIVATE_KEY: ${{ inputs.key }}
    - name: Container Name
      run: echo CONTAINER_NAME=${GITHUB_REPOSITORY#*/} >> $GITHUB_ENV
      shell: bash
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
    - name: Prune Docker Images
      if: ${{ inputs.prune-gh-pat != '' }}
      uses: vlaurin/action-ghcr-prune@main
      with:
        token: ${{ inputs.prune-gh-pat }}
        container: ${{ env.CONTAINER_NAME }}
        keep-last: 1
        untagged: true
        tag-regex: ".*"
